FROM alpine:3.5

RUN apk update
RUN apk add --no-cache python python-dev build-base py-pip
RUN pip install --upgrade pip
RUN rm -r /root/.cache

ADD defaultBuildCmd /usr/local/bin/build
ADD builder /builder

EXPOSE 8001
